name: Test all actions
run-name: ${{ github.actor }} is running tests
permissions:
  contents: read
  pages: read
  id-token: write

on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upload action
        uses: actions/checkout@v4
        with:
          path: upload-action
      - name: Checkout Azure compliance action
        uses: actions/checkout@v4
        with:
          repository: Omegapoint/cydig-azure-compliance-action
          path: azure-compliance-action
      - name: Checkout compliance action
        uses: actions/checkout@v4
        with:
          repository: Omegapoint/cydig-compliance-action
          path: compliance-action
      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install upload action dependencies
        run: |
          cd upload-action
          npm ci
      - name: Install compliance action dependencies
        run: |
          cd compliance-action 
          npm ci
      - name: Install azure compliance action dependencies
        run: |
          cd azure-compliance-action 
          npm ci

      - name: Run upload tests
        run: |
          cd upload-action
           npm run test
      - name: Run azure compliance tests
        run: |
          cd azure-compliance-action
          npm run test
      - name: Run compliance tests
        run: |
          cd compliance-action
          npm run test

      - name: Build Upload action
        run: |
          cd upload-action 
          npm run build
      - name: Build azure compliance action
        run: |
          cd azure-compliance-action
          npm run build
      - name: Build compliance action
        run: |
          cd compliance-action
          npm run build

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: "Run Azure Compliance Controls"
        uses: ./azure-compliance-action
        with:
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
          cydigConfigPath: ${{ github.workspace }}/azure-compliance-action/src/cydigConfig.json
      - name: "Run Compliance Controls"
        uses: ./compliance-action
        with:
          cydigConfigPath: ${{ github.workspace }}/compliance-action/src/cydigConfig.json
          PAT-token: ${{ secrets.MY_GITHUB_PAT }}

      - name: Set dev func URL
        run: |
          echo "urlUpdate=${{ secrets.URL_UPLOAD_DEV }}" >> $GITHUB_ENV 
          echo "updateKey=${{ secrets.CYDIG_API_KEY_DEV }}" >> $GITHUB_ENV 
          echo "urlDashboard=${{ secrets.URL_DASHBOARD_DEV }}" >> $GITHUB_ENV 
          echo "urlBadgeService=${{ secrets.URL_BADGE_SERVICE_DEV }}" >> $GITHUB_ENV 
          echo "accessKeyBadgeService=${{ secrets.ACCESS_KEY_BADGES_DEV }}" >> $GITHUB_ENV

      - name: "Run Upload Action"
        uses: ./upload-action
        with:
          cydigConfigPath: ${{ github.workspace }}/upload-action/src/cydigConfig.json
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
